### ISSUE TITLE
import twitter produces AttributeError: 'module' object has no attribute 'Http'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gyc2432968/python-twitter#251]
```
What steps will reproduce the problem?
1. import twitter
2.
3.

What is the expected output? expect no output   What do you see instead?
>>> import twitter

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    import twitter
  File "build\bdist.win32\egg\twitter.py", line 63, in <module>
  File "C:\Python27\lib\site-packages\oauth2-1.5.211-py2.7.egg\oauth2\__init__.py", line 615, in <module>
AttributeError: 'module' object has no attribute 'Http'

What version of the product are you using? On what operating system?
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on 
win32

windows 7, 64bit

Please provide any additional information below.

```

Original issue reported on code.google.com by `kar31...@gmail.com` on 3 Apr 2013 at 1:25

**Comment by GoogleCodeExporter** [comment]
```
Can you pull the very latest code - the one that now works with TwitterAPI v1.1

and see if this still happens - thanks
```

Original comment by `bear42` on 13 Jun 2013 at 10:44
